### ISSUE TITLE
Convert Vector Map to Opendrive

### ISSUE THREAD

**Issue by monkeykane** [hatem-darweesh/assuremapingtools#1]
Hi @hatem-darweesh 
Thank you for offering the covert tool. 
when I use assure map editor to import some Vector Map (lgsvl, vector_map_sim_sf_portion), it is always crashed. Some info in Terminal as follow:

----
Before The OpenGL Main Loop
 >> Loading vector map data files ... 
 >> Extracting Lanes ... 
Segmentation fault (core dumped)
----
It seems there are too many points and lanes (over 150K) need to be processed.

BR,
wkwu

p.s.

**Comment by hatem-darweesh** [comment]
@monkeykane can you share the data with me to test this problem.

**Comment by monkeykane** [comment]
@hatem-darweesh 
https://github.com/lgsvl/autoware-data/tree/master/data/map/vector_map_sim_sf_portion

**Comment by hatem-darweesh** [comment]
@monkeykane , something wrong with these maps ! 
I fixed the segmentation fault, but there is some king of shift in the points.csv data file. points ID starts from 2, if changed to start from 0 , the map will visualize correctly. 
also I tried to load using autoware, but autoware failed to load the map.

**Comment by monkeykane** [comment]
@hatem-darweesh 
Thanks for your feedback. I used lgsvl-autoware to load this map, it worked, but frame rate in rviz is very slow, only 1-2 fps

**Comment by hatem-darweesh** [comment]
@monkeykane this map contains too many waypoints, it will always be slow in visualization. 
for the reading part in the map editor , I added another menu item to use different parser.
