### ISSUE TITLE
kml problem

### ISSUE THREAD

**Issue by trustmetao** [hatem-darweesh/assuremapingtools#5]
I used assuremapingtools to draw the vector map, but when load this vector map in autoware which shown  the process has died. I don't know if some of the information is incomplete, anyone help me ?
Besides, I found my kml file's coordinates are 0.
![kml_error](https://user-images.githubusercontent.com/52956223/70889528-c9342680-201d-11ea-87a9-897d3ba00b32.png)
![kml](https://user-images.githubusercontent.com/52956223/70889748-41025100-201e-11ea-9e8b-5d502249d29f.png)

**Comment by hatem-darweesh** [comment]
@trustmetao Sorry for the late comment. 
I found the problem. and I pushed a fix for it. please check. 
now there are two .kml save options. 
1- for google earth visualization, if you have GPS information, you will be able to load the .kml into google earth. 
2- for OpenPlanner which works with Autoware.
